version: '3.8'

services:
  roach1:
    image: cockroachdb/cockroach:v24.2.1
    container_name: roach1
    networks:
      - roachnet
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - roach1:/cockroach/cockroach-data
    command: start --insecure --advertise-addr=10.35.141.253 --join=10.35.141.253,10.35.141.78 --cache=.25 --max-sql-memory=.25

networks:
  roachnet:
    driver: bridge

volumes:
  roach1: