version: '3.8'

services:
  roach1:
    image: cockroachdb/cockroach:v24.2.1
    container_name: roach1
    networks:
      - roachnet
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - roach1:/cockroach/cockroach-data
    command: start --advertise-addr=localhost:26257 --http-addr=localhost:8080 --listen-addr=localhost:26257 --sql-addr=localhost:26257 --insecure --join=localhost:26257,localhost:26258,localhost:26259

  roach2:
    image: cockroachdb/cockroach:v24.2.1
    container_name: roach2
    networks:
      - roachnet
    ports:
      - "26258:26257"
      - "8081:8080"
    volumes:
      - roach2:/cockroach/cockroach-data
    command: start --advertise-addr=localhost:26258 --http-addr=localhost:8081 --listen-addr=localhost:26258 --sql-addr=localhost:26258 --insecure --join=localhost:26257,localhost:26258,localhost:26259

  roach3:
    image: cockroachdb/cockroach:v24.2.1
    container_name: roach3
    networks:
      - roachnet
    ports:
      - "26259:26257"
      - "8082:8080"
    volumes:
      - roach3:/cockroach/cockroach-data
    command: start --advertise-addr=localhost:26259 --http-addr=localhost:8082 --listen-addr=localhost:26259 --sql-addr=localhost:26259 --insecure --join=localhost:26257,localhost:26258,localhost:26259

networks:
  roachnet:
    driver: bridge

volumes:
  roach1:
  roach2:
  roach3:
